### ISSUE TITLE
SelectedIndex not working as expected for DropDown combo box

### ISSUE THREAD

**Issue by PaulBol** [filipnavara/mac-playground#10]
I noticed that `ComboBox.SelectedIndex` does not have the expected value -1 when text was entered which is not part of the list (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedindex?view=netframework-4.7.2).

This can happen with `DropDownStyle = ComboBoxStyle.DropDown`. A user can type any text and hit return. This does not lead to a `SelectedIndexChanged` event. But on Windows `SelectedIndex` will subsequently return -1.

With the current implementation the behavior is different. `ComboTextFieldChanged` does not call `OnImpSelectedItemChanged` since `indexofCompleted == -1`. In turn the combo's `SelectedIndex` will have its old value and not -1.

I believe the right fix is something like 

    if (indexofCompleted != -1)
         owner.OnImpSelectedItemChanged(sender, e);
    else
         owner.SelectedIndexChanged();

in `ComboBoxImp.ComboTextFieldChanged` where `SelectedIndexChanged` is a new method that updates `selected_index` but does not raise any events. However, my understanding of the combobox implementation isn't deep enough to submit a pull request without asking.

**Comment by filipnavara** [comment]
You are right. We never really bothered to implement it since we use that style of ComboBox only on one place in our application. I assume dropping the `if (indexofCompleted != -1)` condition would work, but I cannot test it right now and I'll be away until the new year.

**Comment by PaulBol** [comment]
Thanks for your feedback. Dropping `if (indexofCompleted != -1)` would always lead to a `SelectedIndexChanged` event because `OnImpSelectedItemChanged` calls `OnSelectedIndexChanged`. I tested on Windows and here no `SelectedIndexChanged` event occurs when `SelectedIndex` changes to -1 (though [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedindexchanged?view=netframework-4.7.2) unconditionally says "Occurs when the SelectedIndex property has changed.")

Therefore I thought updating `selected_index` without raising `SelectedIndexChanged` would be better. Anyways, let me know which way you prefer when you have a chance in the new year.

**Comment by PaulBol** [comment]
@filipnavara Just wanted to check if you had the chance to consider what would be the preferred solution. Happy to help implementing.

**Comment by filipnavara** [comment]
@PaulBol I got stuck on couple of other issues, so I didn't get to implement the appropriate test code (eg. something in FormsTest application). The original managed implementation of ComboBox in the Mono code doesn't seem to match the behavior you describe. It could very well be broken, but it seems that the code in `ComboBox.Mac` tried to imitate the behavior there.

Let's suppose that both `ComboBox` and `ComboBox.Mac` are not implementing the same behavior as in Windows. In that case I still believe that it should go through `OnImpSelectedItemChanged` and optionally skip calling the events (either by specifying it in an optional `bool` parameter, or by a `selectedIndex != -1` condition). Aside from that the current implementation of `ComboBoxImp.IndexOfSelectedItem` deliberately tries to return the index of the last selected item, which should be addressed as well.

**Comment by PaulBol** [comment]
I see, thanks for explaining. Keeping `ComboBox` and `ComboBox.Mac` consistent makes sense. Then all that's needed is dropping `if (indexofCompleted != -1)` like you already suggested.

I could not find a flaw in `ComboBoxImp.IndexOfSelectedItem`. From what I saw `indexofCompleted` is -1 after typing text that is not auto-completed to an existing item. When I tested `selected_index = imp.IndexOfSelectedItem` set `selected_index` to -1.

**Comment by PaulBol** [comment]
Thanks for merging the PR @filipnavara.

On a related note, I submitted a fix to sysdrawing-coregraphics but it doesn't get much attention (https://github.com/mono/sysdrawing-coregraphics/pull/29). Are you in touch with anyone who can help?

**Comment by filipnavara** [comment]
@PaulBol yep, will push it through.

**Comment by PaulBol** [comment]
Excellent, thanks! And sorry for the off-topic note this thread. I'll close it.
