### ISSUE TITLE
ApplicationShouldTerminate without main form

### ISSUE THREAD

**Issue by PaulBol** [filipnavara/mac-playground#2]
First of all, great SWF Cocoa port!

I tried to run it for an application that does not have a main window which is always present. One thing I noticed is that the `ApplicationShouldTerminate` event is not received when no form is open.

I tracked this down to the call `NSApp.NextEvent(dequeue:=false)` which apparently does not process `ApplicationShouldTerminate`. `NSApp.NextEvent(dequeue:=true)` does.

Therefore I'm suggesting the attached patch. Would you mind reviewing if the suggested change makes sense?

[XplatUICocoa.cs.patch.zip](https://github.com/filipnavara/mac-playground/files/2663203/XplatUICocoa.cs.patch.zip)

**Comment by filipnavara** [comment]
I'll look at the code this week once I return to office. We generally prefer GitHub pull requests for code contributions to simplify and accelerate the review process, but we are happy for any help.

**Comment by PaulBol** [comment]
Let me try to send a pull request. I'm not so experienced with GitHub yet - good opportunity to learn.

**Comment by PaulBol** [comment]
PR https://github.com/filipnavara/mac-playground/pull/3 submitted.
