### ISSUE TITLE
Where is MonoMac.dll from

### ISSUE THREAD

**Issue by joyinfo** [filipnavara/mac-playground#23]
I see the MonoMac.dll in root directory and wonder where it is from? 

I see two related projects below, is it related with these two projects?
  https://github.com/mono/monomac
  https://github.com/xamarin/xamarin-macios

Thanks.

**Comment by filipnavara** [comment]
It is a leftover. We originally used MonoMac (from your first link) but it is old, unmaintained and 32-bit only. We made some effort to fix bugs and port it to 64-bit. There was a whole source code of that effort hosted in this repository and this file was just a build artifact from it. Eventually Microsoft bought Xamarin and open sourced it. We migrated to Xamarin.Mac (your second link) and the rest is history.

**Comment by joyinfo** [comment]
Thanks
