### ISSUE TITLE
Reference to MailClient.BuildTasks.targets: cannot find that file

### ISSUE THREAD

**Issue by fairflow** [filipnavara/mac-playground#29]
[Disclaimer: I am new to building WinForms applications using Visual Studio and completely new to mac-playground]

Setup and background:
running 10.15.3 (Catalina) which being 64bit cannot run WinForms apps out of the box
running VS for Mac 8.4.8
Xamarin.Mac Version: 6.10.0.21 (Visual Studio Community)
cloned mac-playground into fresh directory
build fails as the file above does not exist

Purpose:
I want to try using mac-playground as a way forward to recompiling my old WinForms application; but
tried a search and StackOverflow sites but finding nothing

**Comment by filipnavara** [comment]
Sorry about that. The sources mirror part of our internal product tree which contains the file outside the public part. I'll try to fix the build ASAP.

**Comment by fairflow** [comment]
Great thanks for rapid response.

**Comment by filipnavara** [comment]
I won't be able to fix the build properly until Monday morning. I created a branch with a fix that you can apply now: https://github.com/emclient/mac-playground/tree/fix-build

**Comment by fairflow** [comment]
Great, that fixed that problem.  Now however I find MailClient.Collections and MailClient.Common.UI assemblies are missing though, should I raise a new issue?

**Comment by fairflow** [comment]
Apologies, I think I didn't checkout the branch properly, I have it working now.  Still learning my git client!

**Comment by filipnavara** [comment]
> Now however I find MailClient.Collections and MailClient.Common.UI assemblies are missing though, should I raise a new issue?

We have some custom controls in our project and sometimes the references to them sneak into the test app. I try to clean it up as soon as that happens but unfortunately the automatic mirroring for this project was broken for few months. That resulted in quite a big backlog of issues that I need to cleanup. Sorry for the trouble.

**Comment by filipnavara** [comment]
This should be fixed by now.
