### ISSUE TITLE
The type initializer threw an exception

### ISSUE THREAD

**Issue by DualDestry** [filipnavara/mac-playground#31]
I heard that this application allows users to use x64bit winforms on MacOS. I tried to follow the instructions in the readme and I got this while opening up the .sln file:

Error while trying to load the project '*filepath*/mac-playground-master/FormsTestApp/FormsTest.app.csproj': The type initializer for 'MonoDevelop.MonoMac.XamMac2ProjectFlavor' threw an exception.

**Comment by filipnavara** [comment]
Do you have Xamarin.Mac installed in the Visual Studio for Mac installation?

**Comment by filipnavara** [comment]
This should be fixed by now; the latest version builds with .NET 6 and requires updated tooling.
