### ISSUE TITLE
dotNet 7.0 update

### ISSUE THREAD

**Issue by KyleKrein** [filipnavara/mac-playground#37]
Tried to use Winforms on Mac with .Net 7 and there're some assembly errors I wasn't able to resolve.

**Comment by filipnavara** [comment]
I am on vacation till the end of the month so I won't be able to do much until I return. Internally we already have a version running on .NET 7 but I need to find time to fix the git synchronization scripts to update this repository.

**Comment by KyleKrein** [comment]
Looking forward to it! You've done awesome work!

**Comment by filipnavara** [comment]
I just updated the code base to be in sync with our .NET 6-based app code base. I'll follow up with .NET 7 after 7.0.2 servicing lands (which is blocked for catastrophic WinForms bugs on Windows). This should already be possible to reference from .NET 7 app though.
